### ISSUE TITLE
Way to integrate Do Not Track?

### ISSUE THREAD

**Issue by binoculars** [adopted-ember-addons/ember-metrics#200]
Is there a way to check for [DNT](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack)? I imagine this could be a config setting like `respectDNT: true`. I've had users complain, but telling them to use a blocker doesn't go over well.

**Comment by JoepHeijnen** [comment]
I also would like to know if this is available or gonna be implemented. Its related to the GDPR and we need this option. Otherwise I am gonna make a pull request ;)

**Comment by evansims** [comment]
The route I've personally gone is to lazy initialize ember-metrics, per the readme, and only actually activate the adapters when the visitor's `navigator.doNotTrack` is false. I also have some other condition checks around whether they've accepted my GDPR consent dialog to allow tracking, etc.

**Comment by Redsandro** [comment]
Related: https://github.com/poteto/ember-metrics/pull/203

**Comment by jherdman** [comment]
Resolved by #203
