### ISSUE TITLE
Multiple GA tacking codes

### ISSUE THREAD

**Issue by elefante** [adopted-ember-addons/ember-metrics#217]
Some times It's useful to send data to multiple GA accounts from a single site. Maybe parts of this site is managed by different teams, and have different GA accounts.

The GA documentation says that one of them must have a name:

`ga('create', 'UA-XXXXX-Y', 'auto');`
`ga('create', 'UA-XXXXX-Z', 'auto', 'clientTracker');`

Is it possible implement this using ember-metrics?

Great addon, thank you!

**Comment by Leooo** [comment]
To make it work, should allow a fourth optional parameter coming from config in https://github.com/MelSumner/ember-metrics/blob/master/addon/metrics-adapters/google-analytics.js#L42

And also optionally override https://github.com/MelSumner/ember-metrics/blob/master/addon/metrics-adapters/google-analytics.js#L99 and https://github.com/MelSumner/ember-metrics/blob/master/addon/metrics-adapters/google-analytics.js#L83 fromt he same config param as per https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers

Then using different `config` for each metricsAdapter instance should work.

 In our case, to split analytics across engines, we reinstantiate metricsAdapters in an instance-initializer

Will give it a go

**Comment by jherdman** [comment]
Resolved by #269
