### ISSUE TITLE
Analytics NPM Package

### ISSUE THREAD

**Issue by devotox** [adopted-ember-addons/ember-metrics#238]
This could be useful https://getanalytics.io/

**Comment by jherdman** [comment]
This is a very interesting package. It might be very interesting to refactor towards using this package as the engine.

**Comment by Windvis** [comment]
@jherdman While thinking about a potential embroider compatible API for ember-metrics I stumbled on this npm package and it got me thinking. What would this addon look like if that npm package was used behind the scenes?  Is there a benefit of an Ember specific wrapper over using that library directly? The usage instructions seem simple enough and should work perfectly in modern Ember applications.

It might make sense to simply deprecate this addon, recommend that package and write a migration guide instead?

**Comment by jherdman** [comment]
This is a great point, and I'm glad to hear I'm not the only one thinking along these lines.

Back in #16 @blatyo raised the idea of integrating Analytics.is. At the time I didn't see a clear path forward to doing this without breaking everything. This, however, is exactly where we're at now: the major release will be breaking.

Let's think a little bit about a future where we use Analytics.is under the hood:

Pros
----

1. Reduced maintenance burden for this package.
2. Rally around a package that has broad community support.
3. We'd introduce a huge number of adapters that aren't currently available.
4. This library could expose a small number of things. Namely how to bootstrap the underlying package, and providing a Typescript enabled service. Ideally this may even be generated by a blueprint thus allowing the owner application to manage the integration themselves going forward.

Cons
----

1. Massively breaking, and will likely lead to some community frustration.
2. I won't have time to fully explore this option for at least 3 months (I'm on pat leave).

Conclusions
-----------

I really like this idea, but I cannot figure out if we ought to explore one of the following two options:

1. Release an Embroider compatible major version update of this package as-is. Introduce an entirely new package that uses Analytics.js underneath. This approach will requires less risk management.
2. The next major version uses Analytics.js as a `peerDependency`. This approach will need risk carefully managed. We can't afford to introduce a new version that breaks people's metrics integration.

I'd love to hear what people think of the above.
