### ISSUE TITLE
Please release a new version containing fixed issues

### ISSUE THREAD

**Issue by cah-briangantzler** [adopted-ember-addons/ember-metrics#285]
https://github.com/adopted-ember-addons/ember-metrics/issues/277 fixed an implicit this deprecation. Could we get a new release that includes this so that I may update my app. Thanks

**Comment by rmachielse** [comment]
We would also like to get rid of some deprecation messages, it would be great if a release can be done soon 🙏

**Comment by rmachielse** [comment]
@jherdman @Turbo87 anyone who can do this? Is anything keeping this from being released?

**Comment by jherdman** [comment]
Hi @rmachielse! There are currently fails with ember-beta and ember-canary that need to be investigated. Outside of that, it's just me finding some time. Kids + Life, etc.

**Comment by jherdman** [comment]
Which is to say... if you want to investigate the ember-beta and canary fails I'd be very thankful 😁

**Comment by jherdman** [comment]
OK, I'm going to publish a release in a few minutes knowing that it's failing the following scenarios:

- beta
- canary
- all embroider

We'll double back on all of this

**Comment by jherdman** [comment]
Done! v1.3.0
