### ISSUE TITLE
Support Embroider optimized

### ISSUE THREAD

**Issue by Windvis** [adopted-ember-addons/ember-metrics#316]
I was researching if this addon was compatible with Embroider already so I stumbled on this discussion:
https://github.com/adopted-ember-addons/ember-metrics/pull/279#discussion_r628880270

It seems some work needs to be done so I'm opening this issue to track that. :smile:

**Comment by jherdman** [comment]
It looks like the embroider-optimized strategy is failing now, and for good reason. Hopefully we can get there.

**Comment by Windvis** [comment]
I think the easiest way to make this addon Embroider optimized compatible with the current code is to make users import the built-in adapters they want to use. Maybe we can document that in the readme for now and add it to the dummy app as well so CI no longer fails?

It would give us more time to discuss which alternative configuration method we want to go for?
