### ISSUE TITLE
Support for Google Analytics 4

### ISSUE THREAD

**Issue by elwayman02** [adopted-ember-addons/ember-metrics#344]
GA 4 switched from Universal Analytics IDs (e.g. UA-12341234) to Measurement IDs. I tried setting up ember-metrics with the GA adapter and provided the Measurement ID, but it never fired any events. When I switched back to a UA ID, it started working (with no other code changes). It seems that the adapter needs updates to allow people to migrate to the new paradigm.

https://support.google.com/analytics/answer/10759417?hl=en&ref_topic=10737980

**Comment by kennstenicht** [comment]
I have created a pull request with a new GA4 adapter: #437

**Comment by amiarSlimane** [comment]
is G-V4 working for anyone ? for me  it is sending the data , but can't see any data collected from google.

**Comment by dhochbaum-dcp** [comment]
Looks like this functionality was merged on 11/29. @jherdman do you have any info on when the GA4 adapter might be included in a release?

**Comment by jherdman** [comment]
I'll try to get something out this week if someone could test out the integration with their app and verify that it's working as expected.

**Comment by dhochbaum-dcp** [comment]
Hi @jherdman, confirming that I've tested the integration and it worked as expected.

**Comment by jherdman** [comment]
Apologies, I still need to do this release. Holidays, kids, etc. 🎄 🎅🏻 🍾

**Comment by jherdman** [comment]
Please see https://github.com/adopted-ember-addons/ember-metrics/releases/tag/v2.0.0-beta.2
