### ISSUE TITLE
Issues when running `ember test`

### ISSUE THREAD

**Issue by briangonzalez** [adopted-ember-addons/ember-metrics#43]
We're currently experiencing an error when running `ember test` in our app:

```
Attempting to inject an unknown injection: `service:metrics`
```

We currently have over ~150 failing tests due to this issue.

If we add the following, the test passes:

``` diff
moduleForComponent('box-tabs', {
+  needs: ['service:metrics']
});
```

Is the right approach to add in the `needs` in all ~150 failing tests, or, is there a better solution?

**Comment by poteto** [comment]
If you're using a method on the service in a component/controller/route, you'll need to inject it via `needs` in your test. If you're not, then it might be a bug. I suspect it is due to the augmented `LinkComponent`, which I am considering removing.

**Comment by poteto** [comment]
@briangonzalez If you'd like to try it out, you can give 5b1327d1d5fe20931c15efc9d3242328c6e4bb6a a try and see if that helps with tests.

**Comment by briangonzalez** [comment]
@poteto Thanks for the quick turnaround! 

> If you're using a method on the service in a component/controller/route/etc, you'll need to inject it via needs

We're not, so this is most likely a bug. 

@cacuario and I are going to give this a shot tomorrow and we'll keep you posted.

**Comment by briangonzalez** [comment]
This did not fix the issue.

**Comment by poteto** [comment]
*Something* in your component is using the metrics service, it would not throw otherwise. The addon doesn't do any automatic dependency injection into components, so that is an Ember semantic that is entirely opt-in. It is hard to say without knowing the details of the component, but perhaps you could try checking:

1. Are there any mixins involved, or is the component inheriting from another subclass of component? 
1. Are there services being injected into it that have the metrics service injected into them? 
1. Does the component have other components in its template, that use the metrics service?

**Comment by poteto** [comment]
Sidenote: If you're using [`0.4.0`](https://github.com/poteto/ember-metrics/releases/tag/0.4.0), the simplest solution is to make all your adapters work only in `development` and/or `production`, unless you are testing them

**Comment by deepan83** [comment]
I've injected the service into my router to report route transitions to google analytics and unit tests on routes and controllers that don't explicitly inject the service are failing. Is specifying the service as a  dependency on these tests through needs the only way of addressing this?

**Comment by briangonzalez** [comment]
Yes, 100%.

On Monday, February 22, 2016, Deepan Aiyasamy <notifications@github.com>
wrote:

> I've injected the service into my router to report route transitions to
> google analytics and unit tests on routes and controllers that don't
> explicitly inject the service are failing. Is specifying the service as a
> dependency on these tests through needs the only way of addressing this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/poteto/ember-metrics/issues/43#issuecomment-187171133>
> .
>


-- 
–
Brian

**Comment by ashblue** [comment]
We started cleaning up our tests and found this was the cause of 100 failed tests. If we can't fix this easily we'll have to abandon the plugin. Having to inject a need into every test is a rough solution.

**Comment by poteto** [comment]
That is definitely very odd. If you move the page transition track in the router into the application route instead, does the needs still occur?

**Comment by ashblue** [comment]
@poteto Awesome! That magically seems to have fixed it. Still crawling through the error logs for some other issues, but everything looks smooth.

**Comment by poteto** [comment]
Interesting, thanks for finding that out! I will do an update to the README.

**Comment by briangonzalez** [comment]
Is there a better long term solution than moving all tracking to the route?

**Comment by poteto** [comment]
I'll have to investigate, it's still odd that the router would be involved in a component unit / integration test.

**Comment by timjcook** [comment]
We had the same issue, injecting the service into the router broke a lot of unit tests.
We ended up writing a mixin that binds our metrics events to the `Route#activate` hook and included it on all routes that we needed it for. Works well and I kind of like a `Route` being in control of sending its own events.

**Comment by briangonzalez** [comment]
@timjcook Mind sharing the mixin here?

**Comment by timjcook** [comment]
@briangonzalez mixin for basic page tracking looks like this
```javascript
import Ember from 'ember';

export default Ember.Mixin.create({
  metrics: Ember.inject.service(),
  trackCurrentPage: Ember.on('activate', function () {
    Ember.run.scheduleOnce('afterRender', this, () => {
      const page = document.location.pathname;
      const title = this.getWithDefault('routeName', 'unknown');

      Ember.get(this, 'metrics').trackPage({ page, title });
    });
  })
});
```
props to @antonivanopoulos

**Comment by GCheung55** [comment]
Just got bit by this issue.

**Comment by briangonzalez** [comment]
@GCheung55 

We've gotten around this issue using blueprints at Dollar Shave Club:

```
my-app/blueprints/route-test/files/tests/unit/routes/__test__.js
```

```
import { moduleFor, test } from 'ember-qunit';
import TestConfig from 'my-app/tests/config';

moduleFor('route:<%= dasherizedModuleName %>', {
  needs: TestConfig.defaultRouterNeeds.concat([
    // Specify the other units that are required for this test.
  ]),
});

// Replace this with your real tests.
test('it exists', function itExists(assert) {
  const route = this.subject();
  assert.notOk(route, 'It shoud have a real test');
});
```

**Comment by alexander-alvarez** [comment]
unless need to verify that the page transitions are working in your tests, I worked around it like so
`router.js`
```js
if (config.environment !== 'test') {
    ApplicationRouter.reopen({
        metrics: inject.service(),
        ...
    });
}

```

**Comment by nishant011093** [comment]
# using needs: ['service:i18n'] but the unit test is failing when it comes to inject service in unit test.
 code of the unit test is as follows:-

import Ember from 'ember';
import GroupColumnHeadersMixin from 'hoppr-ui/mixins/group-column-headers';
import { moduleFor, test } from 'ember-qunit';

const { getOwner } = Ember;

moduleFor('mixin:group column headers','Unit | Mixin | group column headers', {
  needs: ['service:i18n'],
  subject() {
    let GroupColumnHeadersObject = Ember.Object.extend(GroupColumnHeadersMixin);
    this.register('test-container: group-column-headers-object',GroupColumnHeadersObject);
    return getOwner(this).lookup('test-container: group-column-headers-object');
  }
});

test('it works', function(assert) {
  let subject = this.subject();
  let i18n = subject.get('i18n');
  assert.ok(subject);
  assert.ok((subject.actual().name.toString()).match('Actual'));
  assert.ok(subject.forecast().name.match('FCST'));
  assert.ok(subject.mtd().name.match('Month To Date'));
  assert.ok(subject.forcast_mtd().name.match('Forecast MTD'));
  assert.ok(subject.variance_mtd().name.match('Variance MTD'));
  assert.ok(subject.ly_mtd.name().match('Last Year MTD'));
  assert.ok(subject.variance_ly_mtd().name.match('Variance Last Year'));
  assert.ok(subject.budget().name.match('Budget'));
  assert.ok(subject.ly_budget().name.match("Last Year Budget"));
  assert.ok(subject.mtd_budget().name.match("MTD Budget"));
  assert.ok(subject.mtd_budget_variance().name.match("MTD Budget Variance"));
  assert.ok(subject.lytd_budget().name.match("LYTD Budget"));
  assert.equal(subject.getFixedColumns().length,2);
  assert.equal(subject.getDraggableColumns().length,10);
});

**Comment by timjcook** [comment]
@nishant011093 could you go into some more details here mate? we're not here to just fix your tests.

**Comment by timjcook** [comment]
@nishant011093 best way to get an answer in these forums is to have a conversation, not just copy paste code 😄  Feel free to tag me if you want to explain you issue further. Good luck.

**Comment by jherdman** [comment]
Is this still a relevant issue?

**Comment by jherdman** [comment]
Stale. Closing.
