### ISSUE TITLE
Release 1.5.0 accidentally shipped breaking changes meant for v2?

### ISSUE THREAD

**Issue by jaswilli** [adopted-ember-addons/ember-metrics#442]
Hi!

The 1.5.0 release that just shipped included https://github.com/adopted-ember-addons/ember-metrics/pull/372 which seems to have been intended for a v2 release?

**Comment by rwwagner90** [comment]
@jherdman any thoughts on releasing a v2 beta? We're updating to 1.5.0 and this is not a breaking change for us.

**Comment by jherdman** [comment]
I'll do both: v1.5.1 that reverts this change, and a v2 beta.

**Comment by jherdman** [comment]
Done!

My apologies for this mess, friends. I made the noted change on my pat-leave and had forgotten about it.

**Comment by jaswilli** [comment]
Sounds good to me.

I have a diff ready to handle the v2 changes in my project so I can move to the beta when it's released for some additional testing.
