### ISSUE TITLE
Could not find metrics adapter GoogleAnalytics

### ISSUE THREAD

**Issue by JamieCressey** [adopted-ember-addons/ember-metrics#69]
I'm attempting to add ember-metrics to my Ember project, starting with Google Analytics.

I've set my `app/router.js` and `config/environment.js` as per this projects README:

`config/environment.js`

```
var ENV = {
...
    metricsAdapters: [
      {
        name: 'GoogleAnalytics',
        environments: ['all'],
        config: {
          id: 'UA-XXXX-Y'
        }
      }
    ],
...
}
```

`app/router.js`

```
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
  metrics: Ember.inject.service(),

  didTransition() {
    this._super();
    this._trackPage();
  },

  _trackPage() {
    Ember.run.scheduleOnce('afterRender', this, () => {
      const page = document.location.pathname;
      const title = this.getWithDefault('currentRouteName', 'unknown');

      Ember.get(this, 'metrics').trackPage({ page, title });
    });
  }
});

export default Router;
```

However I don't see the GA code snippet being inserted into my compiled JS, and I am getting the following error in my dev console

``````
Uncaught Error: Assertion Failed: [ember-metrics] Could not find metrics adapter GoogleAnalytics.assert @ ember.debug.js:6254assert @ ember.debug.js:16075_activateAdapter @ metrics.js:223(anonymous function) @ metrics.js:148activateAdapters @ metrics.js:145init @ metrics.js:90superWrapper @ ember.debug.js:22633Class @ ember.debug.js:36144ClassMixinProps.create @ ember.debug.js:36422instantiate @ ember.debug.js:1511lookup @ ember.debug.js:1361Container.lookup @ ember.debug.js:1291(anonymous function) @ ember.debug.js:32719injectedPropertyGet @ ember.debug.js:16861ComputedPropertyPrototype.get @ ember.debug.js:14893get @ ember.debug.js:20290(anonymous function) @ router.js:19Queue.invoke @ ember.debug.js:327Queue.flush @ ember.debug.js:391DeferredActionQueues.flush @ ember.debug.js:192Backburner.end @ ember.debug.js:570Backburner.run @ ember.debug.js:692Backburner.join @ ember.debug.js:712run.join @ ember.debug.js:20709(anonymous function) @ ember.debug.js:20772fire @ jquery.js:3099self.fireWith @ jquery.js:3211jQuery.extend.ready @ jquery.js:3417completed @ jquery.js:3433```

Is there something I'm missing?
``````

**Comment by poteto** [comment]
I'll look into it, seems like an issue with the tree shaking feature. If you type `requirejs.entries` into your console, do you see the path to the ember-metrics google analytics adapter listed?

**Comment by tbarho** [comment]
+1  only adapters listed for me are base and mixpanel.  anyone else besides us having this issue?

**Comment by jorgelainfiesta** [comment]
@JamieCressey @tbarho  I had the same issue, but it was because I did not restart ember server after editing `config`. When I did, everything worked wonderfully.

**Comment by oskarrough** [comment]
Having the same issue, can't see the GA code being inserted and `requirejs.enties` only lists the base-adapter. Restarting and reinstalling the addon didn't help. Any ideas?

**Comment by oskarrough** [comment]
OK, adding this to config/environment.js fixed it for me:

```
'ember-metrics': {
  includeAdapters: ['google-analytics']
},
```

As the readme mentions this shouldn't be necessary I assume there's a bug to track down (or the readme could be changed).

**Comment by jorgelainfiesta** [comment]
@oskarrough if you're using lazy initialization, you do need to include that explicitly. But if that's not your case, there might be something to check.

**Comment by oskarrough** [comment]
@jorgelainfiesta I'm not using lazy initialization. Should I be able to see the analytics script injected in the DOM? If so, it's not there. I'm using ember 2.7.0.

**Comment by montoias** [comment]
I am having the same problem as @oskarrough

**Comment by poteto** [comment]
What version of ember-cli?

**Comment by montoias** [comment]
Hey @poteto, the versions are:

ember-cli: 2.10.0
node: 6.9.1

**Comment by deepflame** [comment]
had the same problem but it worked when I stopped `ember serve`, deleted the `tmp` folder and started the server again.

My config:
ember-cli: 2.12.1
node: 6.9.1

**Comment by rwwagner90** [comment]
I'm seeing this error, but only when running unit tests. I've put this everywhere:

```js
'ember-metrics': {
  includeAdapters: ['google-analytics']
},
```

**Comment by jherdman** [comment]
Closing. Stale.
