### ISSUE TITLE
Pass in a hash of integrations instead of a string to the service

### ISSUE THREAD

**Issue by poteto** [adopted-ember-addons/ember-metrics#9]
e.g.

``` js
metrics.trackEvent({
  integrations: {
    GoogleAnalytics: true,
    Mixpanel: false,
    'customer.io': true
  },
  event: 'foo',
  action: 'bar'
});
```

Potential issues:
- What if I want to send a property to the analytics service that is called `integrations`?
  - possible solutions – prefix `integrations`, pass in 2 objects as args

**Comment by gabrielgrant** [comment]
I like your current API with an optional `analyticsName` better than mixing config into the data. If these are just binary flags, would accepting an array of strings as the `analyticsName` param make sense?

**Comment by jherdman** [comment]
Closing. Stale.
